# Generated by Django 2.2 on 2019-04-19 18:37

import baseauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
                ('objects', baseauth.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
